spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resetkeyoutbox?autoreconnect=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: springtest
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0